- alias: Notify Telegram on alarm binary_sensor ON
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.b01_avariia_datchika_ksiloroda
        - binary_sensor.b01_avariia_kormushka_1
        - binary_sensor.b01_avariia_kormushka_2
        - binary_sensor.b01_avariia_nizkaia_temperatura
        - binary_sensor.b01_avariia_nizkii_kislorod
        - binary_sensor.b01_avariia_oksigeneratora
        - binary_sensor.b01_avariia_vysokaia_temperatura
        - binary_sensor.b01_avariia_vysokii_kislorod
        - binary_sensor.b02_avariia_datchika_ksiloroda
        - binary_sensor.b02_avariia_kormushka_1
        - binary_sensor.b02_avariia_kormushka_2
        - binary_sensor.b02_avariia_nizkaia_temperatura
        - binary_sensor.b02_avariia_nizkii_kislorod
        - binary_sensor.b02_avariia_oksigeneratora
        - binary_sensor.b02_avariia_vysokaia_temperatura
        - binary_sensor.b02_avariia_vysokii_kislorod
        - binary_sensor.b03_avariia_datchika_ksiloroda
        - binary_sensor.b03_avariia_kormushka_1
        - binary_sensor.b03_avariia_kormushka_2
        - binary_sensor.b03_avariia_nizkaia_temperatura
        - binary_sensor.b03_avariia_nizkii_kislorod
        - binary_sensor.b03_avariia_oksigeneratora
        - binary_sensor.b03_avariia_vysokaia_temperatura
        - binary_sensor.b03_avariia_vysokii_kislorod
        - binary_sensor.b04_avariia_datchika_ksiloroda
        - binary_sensor.b04_avariia_kormushka_1
        - binary_sensor.b04_avariia_kormushka_2
        - binary_sensor.b04_avariia_nizkaia_temperatura
        - binary_sensor.b04_avariia_nizkii_kislorod
        - binary_sensor.b04_avariia_oksigeneratora
        - binary_sensor.b04_avariia_vysokaia_temperatura
        - binary_sensor.b04_avariia_vysokii_kislorod
        - binary_sensor.b05_avariia_datchika_ksiloroda
        - binary_sensor.b05_avariia_kormushka_1
        - binary_sensor.b05_avariia_kormushka_2
        - binary_sensor.b05_avariia_nizkaia_temperatura
        - binary_sensor.b05_avariia_nizkii_kislorod
        - binary_sensor.b05_avariia_oksigeneratora
        - binary_sensor.b05_avariia_vysokaia_temperatura
        - binary_sensor.b05_avariia_vysokii_kislorod
        - binary_sensor.b06_avariia_datchika_ksiloroda
        - binary_sensor.b06_avariia_kormushka_1
        - binary_sensor.b06_avariia_kormushka_2
        - binary_sensor.b06_avariia_nizkaia_temperatura
        - binary_sensor.b06_avariia_nizkii_kislorod
        - binary_sensor.b06_avariia_oksigeneratora
        - binary_sensor.b06_avariia_vysokaia_temperatura
        - binary_sensor.b06_avariia_vysokii_kislorod
        - binary_sensor.b07_avariia_datchika_ksiloroda
        - binary_sensor.b07_avariia_kormushka_1
        - binary_sensor.b07_avariia_kormushka_2
        - binary_sensor.b07_avariia_nizkaia_temperatura
        - binary_sensor.b07_avariia_nizkii_kislorod
        - binary_sensor.b07_avariia_oksigeneratora
        - binary_sensor.b07_avariia_vysokaia_temperatura
        - binary_sensor.b07_avariia_vysokii_kislorod
        - binary_sensor.b08_avariia_datchika_ksiloroda
        - binary_sensor.b08_avariia_kormushka_1
        - binary_sensor.b08_avariia_kormushka_2
        - binary_sensor.b08_avariia_nizkaia_temperatura
        - binary_sensor.b08_avariia_nizkii_kislorod
        - binary_sensor.b08_avariia_oksigeneratora
        - binary_sensor.b08_avariia_vysokaia_temperatura
        - binary_sensor.b08_avariia_vysokii_kislorod
        - binary_sensor.b09_avariia_datchika_ksiloroda
        - binary_sensor.b09_avariia_kormushka_1
        - binary_sensor.b09_avariia_kormushka_2
        - binary_sensor.b09_avariia_nizkaia_temperatura
        - binary_sensor.b09_avariia_nizkii_kislorod
        - binary_sensor.b09_avariia_oksigeneratora
        - binary_sensor.b09_avariia_vysokaia_temperatura
        - binary_sensor.b09_avariia_vysokii_kislorod
        - binary_sensor.b10_avariia_datchika_ksiloroda
        - binary_sensor.b10_avariia_kormushka_1
        - binary_sensor.b10_avariia_kormushka_2
        - binary_sensor.b10_avariia_nizkaia_temperatura
        - binary_sensor.b10_avariia_nizkii_kislorod
        - binary_sensor.b10_avariia_oksigeneratora
        - binary_sensor.b10_avariia_vysokaia_temperatura
        - binary_sensor.b10_avariia_vysokii_kislorod
        - binary_sensor.b11_avariia_datchika_ksiloroda
        - binary_sensor.b11_avariia_kormushka_1
        - binary_sensor.b11_avariia_kormushka_2
        - binary_sensor.b11_avariia_nizkaia_temperatura
        - binary_sensor.b11_avariia_nizkii_kislorod
        - binary_sensor.b11_avariia_oksigeneratora
        - binary_sensor.b11_avariia_vysokaia_temperatura
        - binary_sensor.b11_avariia_vysokii_kislorod
        - binary_sensor.b12_avariia_datchika_ksiloroda
        - binary_sensor.b12_avariia_kormushka_1
        - binary_sensor.b12_avariia_kormushka_2
        - binary_sensor.b12_avariia_nizkaia_temperatura
        - binary_sensor.b12_avariia_nizkii_kislorod
        - binary_sensor.b12_avariia_oksigeneratora
        - binary_sensor.b12_avariia_vysokaia_temperatura
        - binary_sensor.b12_avariia_vysokii_kislorod
        - binary_sensor.b13_avariia_datchika_ksiloroda
        - binary_sensor.b13_avariia_kormushka_1
        - binary_sensor.b13_avariia_kormushka_2
        - binary_sensor.b13_avariia_nizkaia_temperatura
        - binary_sensor.b13_avariia_nizkii_kislorod
        - binary_sensor.b13_avariia_oksigeneratora
        - binary_sensor.b13_avariia_vysokaia_temperatura
        - binary_sensor.b13_avariia_vysokii_kislorod
        - binary_sensor.b14_avariia_datchika_ksiloroda
        - binary_sensor.b14_avariia_kormushka_1
        - binary_sensor.b14_avariia_kormushka_2
        - binary_sensor.b14_avariia_nizkaia_temperatura
        - binary_sensor.b14_avariia_nizkii_kislorod
        - binary_sensor.b14_avariia_oksigeneratora
        - binary_sensor.b14_avariia_vysokaia_temperatura
        - binary_sensor.b14_avariia_vysokii_kislorod
        - binary_sensor.b15_avariia_datchika_ksiloroda
        - binary_sensor.b15_avariia_kormushka_1
        - binary_sensor.b15_avariia_kormushka_2
        - binary_sensor.b15_avariia_nizkaia_temperatura
        - binary_sensor.b15_avariia_nizkii_kislorod
        - binary_sensor.b15_avariia_oksigeneratora
        - binary_sensor.b15_avariia_vysokaia_temperatura
        - binary_sensor.b15_avariia_vysokii_kislorod
        - binary_sensor.b16_avariia_datchika_ksiloroda
        - binary_sensor.b16_avariia_kormushka_1
        - binary_sensor.b16_avariia_kormushka_2
        - binary_sensor.b16_avariia_nizkaia_temperatura
        - binary_sensor.b16_avariia_nizkii_kislorod
        - binary_sensor.b16_avariia_oksigeneratora
        - binary_sensor.b16_avariia_vysokaia_temperatura
        - binary_sensor.b16_avariia_vysokii_kislorod
        - binary_sensor.b17_avariia_datchika_ksiloroda
        - binary_sensor.b17_avariia_kormushka_1
        - binary_sensor.b17_avariia_kormushka_2
        - binary_sensor.b17_avariia_nizkaia_temperatura
        - binary_sensor.b17_avariia_nizkii_kislorod
        - binary_sensor.b17_avariia_oksigeneratora
        - binary_sensor.b17_avariia_vysokaia_temperatura
        - binary_sensor.b17_avariia_vysokii_kislorod
        - binary_sensor.b18_avariia_datchika_ksiloroda
        - binary_sensor.b18_avariia_kormushka_1
        - binary_sensor.b18_avariia_kormushka_2
        - binary_sensor.b18_avariia_nizkaia_temperatura
        - binary_sensor.b18_avariia_nizkii_kislorod
        - binary_sensor.b18_avariia_oksigeneratora
        - binary_sensor.b18_avariia_vysokaia_temperatura
        - binary_sensor.b18_avariia_vysokii_kislorod
        - binary_sensor.b19_avariia_datchika_ksiloroda
        - binary_sensor.b19_avariia_kormushka_1
        - binary_sensor.b19_avariia_kormushka_2
        - binary_sensor.b19_avariia_nizkaia_temperatura
        - binary_sensor.b19_avariia_nizkii_kislorod
        - binary_sensor.b19_avariia_oksigeneratora
        - binary_sensor.b19_avariia_vysokaia_temperatura
        - binary_sensor.b19_avariia_vysokii_kislorod
        - binary_sensor.b20_avariia_datchika_ksiloroda
        - binary_sensor.b20_avariia_kormushka_1
        - binary_sensor.b20_avariia_kormushka_2
        - binary_sensor.b20_avariia_nizkaia_temperatura
        - binary_sensor.b20_avariia_nizkii_kislorod
        - binary_sensor.b20_avariia_oksigeneratora
        - binary_sensor.b20_avariia_vysokaia_temperatura
        - binary_sensor.b20_avariia_vysokii_kislorod
        - binary_sensor.b51_avariia_datchika_ksiloroda
        - binary_sensor.b51_avariia_kormushka_1
        - binary_sensor.b51_avariia_kormushka_2
        - binary_sensor.b51_avariia_nizkaia_temperatura
        - binary_sensor.b51_avariia_nizkii_kislorod
        - binary_sensor.b51_avariia_oksigeneratora
        - binary_sensor.b51_avariia_vysokaia_temperatura
        - binary_sensor.b51_avariia_vysokii_kislorod
        - binary_sensor.b52_avariia_datchika_ksiloroda
        - binary_sensor.b52_avariia_kormushka_1
        - binary_sensor.b52_avariia_kormushka_2
        - binary_sensor.b52_avariia_nizkaia_temperatura
        - binary_sensor.b52_avariia_nizkii_kislorod
        - binary_sensor.b52_avariia_oksigeneratora
        - binary_sensor.b52_avariia_vysokaia_temperatura
        - binary_sensor.b52_avariia_vysokii_kislorod
        - binary_sensor.b53_avariia_datchika_ksiloroda
        - binary_sensor.b53_avariia_kormushka_1
        - binary_sensor.b53_avariia_kormushka_2
        - binary_sensor.b53_avariia_nizkaia_temperatura
        - binary_sensor.b53_avariia_nizkii_kislorod
        - binary_sensor.b53_avariia_oksigeneratora
        - binary_sensor.b53_avariia_vysokaia_temperatura
        - binary_sensor.b53_avariia_vysokii_kislorod
        - binary_sensor.b54_avariia_datchika_ksiloroda
        - binary_sensor.b54_avariia_kormushka_1
        - binary_sensor.b54_avariia_kormushka_2
        - binary_sensor.b54_avariia_nizkaia_temperatura
        - binary_sensor.b54_avariia_nizkii_kislorod
        - binary_sensor.b54_avariia_oksigeneratora
        - binary_sensor.b54_avariia_vysokaia_temperatura
        - binary_sensor.b54_avariia_vysokii_kislorod
        - binary_sensor.b55_avariia_datchika_ksiloroda
        - binary_sensor.b55_avariia_kormushka_1
        - binary_sensor.b55_avariia_kormushka_2
        - binary_sensor.b55_avariia_nizkaia_temperatura
        - binary_sensor.b55_avariia_nizkii_kislorod
        - binary_sensor.b55_avariia_oksigeneratora
        - binary_sensor.b55_avariia_vysokaia_temperatura
        - binary_sensor.b55_avariia_vysokii_kislorod
        - binary_sensor.b56_avariia_datchika_ksiloroda
        - binary_sensor.b56_avariia_kormushka_1
        - binary_sensor.b56_avariia_kormushka_2
        - binary_sensor.b56_avariia_nizkaia_temperatura
        - binary_sensor.b56_avariia_nizkii_kislorod
        - binary_sensor.b56_avariia_oksigeneratora
        - binary_sensor.b56_avariia_vysokaia_temperatura
        - binary_sensor.b56_avariia_vysokii_kislorod
        - binary_sensor.b57_avariia_datchika_ksiloroda
        - binary_sensor.b57_avariia_kormushka_1
        - binary_sensor.b57_avariia_kormushka_2
        - binary_sensor.b57_avariia_nizkaia_temperatura
        - binary_sensor.b57_avariia_nizkii_kislorod
        - binary_sensor.b57_avariia_oksigeneratora
        - binary_sensor.b57_avariia_vysokaia_temperatura
        - binary_sensor.b57_avariia_vysokii_kislorod
        - binary_sensor.b58_avariia_datchika_ksiloroda
        - binary_sensor.b58_avariia_kormushka_1
        - binary_sensor.b58_avariia_kormushka_2
        - binary_sensor.b58_avariia_nizkaia_temperatura
        - binary_sensor.b58_avariia_nizkii_kislorod
        - binary_sensor.b58_avariia_oksigeneratora
        - binary_sensor.b58_avariia_vysokaia_temperatura
        - binary_sensor.b58_avariia_vysokii_kislorod
        - binary_sensor.b59_avariia_datchika_ksiloroda
        - binary_sensor.b59_avariia_kormushka_1
        - binary_sensor.b59_avariia_kormushka_2
        - binary_sensor.b59_avariia_nizkaia_temperatura
        - binary_sensor.b59_avariia_nizkii_kislorod
        - binary_sensor.b59_avariia_oksigeneratora
        - binary_sensor.b59_avariia_vysokaia_temperatura
        - binary_sensor.b59_avariia_vysokii_kislorod
        - binary_sensor.b60_avariia_datchika_ksiloroda
        - binary_sensor.b60_avariia_kormushka_1
        - binary_sensor.b60_avariia_kormushka_2
        - binary_sensor.b60_avariia_nizkaia_temperatura
        - binary_sensor.b60_avariia_nizkii_kislorod
        - binary_sensor.b60_avariia_oksigeneratora
        - binary_sensor.b60_avariia_vysokaia_temperatura
        - binary_sensor.b60_avariia_vysokii_kislorod
        - binary_sensor.b61_avariia_datchika_ksiloroda
        - binary_sensor.b61_avariia_kormushka_1
        - binary_sensor.b61_avariia_kormushka_2
        - binary_sensor.b61_avariia_nizkaia_temperatura
        - binary_sensor.b61_avariia_nizkii_kislorod
        - binary_sensor.b61_avariia_oksigeneratora
        - binary_sensor.b61_avariia_vysokaia_temperatura
        - binary_sensor.b61_avariia_vysokii_kislorod
        - binary_sensor.b62_avariia_datchika_ksiloroda
        - binary_sensor.b62_avariia_kormushka_1
        - binary_sensor.b62_avariia_kormushka_2
        - binary_sensor.b62_avariia_nizkaia_temperatura
        - binary_sensor.b62_avariia_nizkii_kislorod
        - binary_sensor.b62_avariia_oksigeneratora
        - binary_sensor.b62_avariia_vysokaia_temperatura
        - binary_sensor.b62_avariia_vysokii_kislorod
        - binary_sensor.b63_avariia_datchika_ksiloroda
        - binary_sensor.b63_avariia_kormushka_1
        - binary_sensor.b63_avariia_kormushka_2
        - binary_sensor.b63_avariia_nizkaia_temperatura
        - binary_sensor.b63_avariia_nizkii_kislorod
        - binary_sensor.b63_avariia_oksigeneratora
        - binary_sensor.b63_avariia_vysokaia_temperatura
        - binary_sensor.b63_avariia_vysokii_kislorod
        - binary_sensor.b64_avariia_datchika_ksiloroda
        - binary_sensor.b64_avariia_kormushka_1
        - binary_sensor.b64_avariia_kormushka_2
        - binary_sensor.b64_avariia_nizkaia_temperatura
        - binary_sensor.b64_avariia_nizkii_kislorod
        - binary_sensor.b64_avariia_oksigeneratora
        - binary_sensor.b64_avariia_vysokaia_temperatura
        - binary_sensor.b64_avariia_vysokii_kislorod
        - binary_sensor.b65_avariia_datchika_ksiloroda
        - binary_sensor.b65_avariia_kormushka_1
        - binary_sensor.b65_avariia_kormushka_2
        - binary_sensor.b65_avariia_nizkaia_temperatura
        - binary_sensor.b65_avariia_nizkii_kislorod
        - binary_sensor.b65_avariia_oksigeneratora
        - binary_sensor.b65_avariia_vysokaia_temperatura
        - binary_sensor.b65_avariia_vysokii_kislorod
        - binary_sensor.b66_avariia_datchika_ksiloroda
        - binary_sensor.b66_avariia_kormushka_1
        - binary_sensor.b66_avariia_kormushka_2
        - binary_sensor.b66_avariia_nizkaia_temperatura
        - binary_sensor.b66_avariia_nizkii_kislorod
        - binary_sensor.b66_avariia_oksigeneratora
        - binary_sensor.b66_avariia_vysokaia_temperatura
        - binary_sensor.b66_avariia_vysokii_kislorod
        - binary_sensor.b67_avariia_datchika_ksiloroda
        - binary_sensor.b67_avariia_kormushka_1
        - binary_sensor.b67_avariia_kormushka_2
        - binary_sensor.b67_avariia_nizkaia_temperatura
        - binary_sensor.b67_avariia_nizkii_kislorod
        - binary_sensor.b67_avariia_oksigeneratora
        - binary_sensor.b67_avariia_vysokaia_temperatura
        - binary_sensor.b67_avariia_vysokii_kislorod
        - binary_sensor.b68_avariia_datchika_ksiloroda
        - binary_sensor.b68_avariia_kormushka_1
        - binary_sensor.b68_avariia_kormushka_2
        - binary_sensor.b68_avariia_nizkaia_temperatura
        - binary_sensor.b68_avariia_nizkii_kislorod
        - binary_sensor.b68_avariia_oksigeneratora
        - binary_sensor.b68_avariia_vysokaia_temperatura
        - binary_sensor.b68_avariia_vysokii_kislorod
        - binary_sensor.b69_avariia_datchika_ksiloroda
        - binary_sensor.b69_avariia_kormushka_1
        - binary_sensor.b69_avariia_kormushka_2
        - binary_sensor.b69_avariia_nizkaia_temperatura
        - binary_sensor.b69_avariia_nizkii_kislorod
        - binary_sensor.b69_avariia_oksigeneratora
        - binary_sensor.b69_avariia_vysokaia_temperatura
        - binary_sensor.b69_avariia_vysokii_kislorod
        - binary_sensor.b70_avariia_datchika_ksiloroda
        - binary_sensor.b70_avariia_kormushka_1
        - binary_sensor.b70_avariia_kormushka_2
        - binary_sensor.b70_avariia_nizkaia_temperatura
        - binary_sensor.b70_avariia_nizkii_kislorod
        - binary_sensor.b70_avariia_oksigeneratora
        - binary_sensor.b70_avariia_vysokaia_temperatura
        - binary_sensor.b70_avariia_vysokii_kislorod
  condition:
    - condition: template
      value_template: "{{ trigger.to_state.state == 'on' }}"
  action:
    - service: notify.telegram
      data:
        message: >
          ‼️ {{ trigger.to_state.attributes.friendly_name }} ‼️
          (бассейн {{ trigger.entity_id.split(".")[1][1:3] }})
  mode: queued