# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

logger:
  default: warning
  logs:
    feeding: info
    feeding_api: debug
    pools_plc: debug
    homeassistant.helpers.entity: debug

lovelace:
  mode: yaml
  resources:
  - url: /local/upload-csv-card.js
    type: module
  - url: /local/button-card.js
    type: module

feeding_plc:
  - host: 192.168.0.201
    number: 1
    pool_plc_index: 1
  - host: 192.168.0.201
    number: 2
    pool_plc_index: 2
  - host: 192.168.0.201
    number: 3
    pool_plc_index: 3
  - host: 192.168.0.201
    number: 4
    pool_plc_index: 4
  - host: 192.168.0.201
    number: 5
    pool_plc_index: 5
  - host: 192.168.0.202
    number: 6
    pool_plc_index: 1
  - host: 192.168.0.202
    number: 7
    pool_plc_index: 2
  - host: 192.168.0.202
    number: 8
    pool_plc_index: 3
  - host: 192.168.0.202
    number: 9
    pool_plc_index: 4
  - host: 192.168.0.202
    number: 10
    pool_plc_index: 5
  - host: 192.168.0.203
    number: 11
    pool_plc_index: 1
  - host: 192.168.0.203
    number: 12
    pool_plc_index: 2
  - host: 192.168.0.203
    number: 13
    pool_plc_index: 3
  - host: 192.168.0.203
    number: 14
    pool_plc_index: 4
  - host: 192.168.0.203
    number: 15
    pool_plc_index: 5
  - host: 192.168.0.204
    number: 16
    pool_plc_index: 1
  - host: 192.168.0.204
    number: 17
    pool_plc_index: 2
  - host: 192.168.0.204
    number: 18
    pool_plc_index: 3
  - host: 192.168.0.204
    number: 19
    pool_plc_index: 4
  - host: 192.168.0.204
    number: 20
    pool_plc_index: 5
  - host: 192.168.0.205
    number: 21
    pool_plc_index: 1
  - host: 192.168.0.205
    number: 22
    pool_plc_index: 2
  - host: 192.168.0.205
    number: 23
    pool_plc_index: 3
  - host: 192.168.0.205
    number: 24
    pool_plc_index: 4
  - host: 192.168.0.205
    number: 25
    pool_plc_index: 5
  - host: 192.168.0.206
    number: 26
    pool_plc_index: 1
  - host: 192.168.0.206
    number: 27
    pool_plc_index: 2
  - host: 192.168.0.206
    number: 28
    pool_plc_index: 3
  - host: 192.168.0.206
    number: 29
    pool_plc_index: 4
  - host: 192.168.0.206
    number: 30
    pool_plc_index: 5
  - host: 192.168.0.207
    number: 31
    pool_plc_index: 1
  - host: 192.168.0.207
    number: 32
    pool_plc_index: 2
  - host: 192.168.0.207
    number: 33
    pool_plc_index: 3
  - host: 192.168.0.207
    number: 34
    pool_plc_index: 4
  - host: 192.168.0.207
    number: 35
    pool_plc_index: 5
  - host: 192.168.0.208
    number: 36
    pool_plc_index: 1
  - host: 192.168.0.208
    number: 37
    pool_plc_index: 2
  - host: 192.168.0.208
    number: 38
    pool_plc_index: 3
  - host: 192.168.0.208
    number: 39
    pool_plc_index: 4
  - host: 192.168.0.208
    number: 40
    pool_plc_index: 5

pools_plc:
  - host: 192.168.0.201
    number: 1
  - host: 192.168.0.202
    number: 2
  - host: 192.168.0.203
    number: 3
  - host: 192.168.0.204
    number: 4
  - host: 192.168.0.205
    number: 5
  - host: 192.168.0.206
    number: 6
  - host: 192.168.0.207
    number: 7
  - host: 192.168.0.208
    number: 8

recorder:
  exclude:
    entity_globs:
      - sensor.b*_sled_korm_1
      - sensor.b*_sled_korm_2
      - sensor.sh*_vremia
