# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

logger:
  default: warning
  logs:
    feeding: info
    feeding_api: debug
    pools_plc: debug
    homeassistant.helpers.entity: debug

lovelace:
  mode: yaml
  resources:
  - url: /local/upload-csv-card.js
    type: module
  - url: /local/button-card.js
    type: module

feeding_plc:
  - host: 192.168.14.20
    number: 1
    pool_plc_index: 1
  - host: 192.168.14.20
    number: 2
    pool_plc_index: 2
  - host: 192.168.14.20
    number: 3
    pool_plc_index: 3
  - host: 192.168.14.20
    number: 4
    pool_plc_index: 4
  - host: 192.168.14.20
    number: 5
    pool_plc_index: 5
  - host: 192.168.14.21
    number: 6
    pool_plc_index: 1
  - host: 192.168.14.21
    number: 7
    pool_plc_index: 2
  - host: 192.168.14.21
    number: 8
    pool_plc_index: 3
  - host: 192.168.14.21
    number: 9
    pool_plc_index: 4
  - host: 192.168.14.21
    number: 10
    pool_plc_index: 5
  - host: 192.168.14.22
    number: 11
    pool_plc_index: 1
  - host: 192.168.14.22
    number: 12
    pool_plc_index: 2
  - host: 192.168.14.22
    number: 13
    pool_plc_index: 3
  - host: 192.168.14.22
    number: 14
    pool_plc_index: 4
  - host: 192.168.14.22
    number: 15
    pool_plc_index: 5
  - host: 192.168.14.23
    number: 16
    pool_plc_index: 1
  - host: 192.168.14.23
    number: 17
    pool_plc_index: 2
  - host: 192.168.14.23
    number: 18
    pool_plc_index: 3
  - host: 192.168.14.23
    number: 19
    pool_plc_index: 4
  - host: 192.168.14.23
    number: 20
    pool_plc_index: 5
  - host: 192.168.14.24
    number: 51
    pool_plc_index: 1
  - host: 192.168.14.24
    number: 52
    pool_plc_index: 2
  - host: 192.168.14.24
    number: 53
    pool_plc_index: 3
  - host: 192.168.14.24
    number: 54
    pool_plc_index: 4
  - host: 192.168.14.24
    number: 55
    pool_plc_index: 5
  - host: 192.168.14.25
    number: 56
    pool_plc_index: 1
  - host: 192.168.14.25
    number: 57
    pool_plc_index: 2
  - host: 192.168.14.25
    number: 58
    pool_plc_index: 3
  - host: 192.168.14.25
    number: 59
    pool_plc_index: 4
  - host: 192.168.14.25
    number: 60
    pool_plc_index: 5
  - host: 192.168.14.26
    number: 61
    pool_plc_index: 1
  - host: 192.168.14.26
    number: 62
    pool_plc_index: 2
  - host: 192.168.14.26
    number: 63
    pool_plc_index: 3
  - host: 192.168.14.26
    number: 64
    pool_plc_index: 4
  - host: 192.168.14.26
    number: 65
    pool_plc_index: 5
  - host: 192.168.14.27
    number: 66
    pool_plc_index: 1
  - host: 192.168.14.27
    number: 67
    pool_plc_index: 2
  - host: 192.168.14.27
    number: 68
    pool_plc_index: 3
  - host: 192.168.14.27
    number: 69
    pool_plc_index: 4
  - host: 192.168.14.27
    number: 70
    pool_plc_index: 5

pools_plc:
  - host: 192.168.14.20
    number: 1
  - host: 192.168.14.21
    number: 2
  - host: 192.168.14.22
    number: 3
  - host: 192.168.14.23
    number: 4
  - host: 192.168.14.24
    number: 11
  - host: 192.168.14.25
    number: 12
  - host: 192.168.14.26
    number: 13
  - host: 192.168.14.27
    number: 14

recorder:
  exclude:
    entity_globs:
      - sensor.b*_sled_korm_1
      - sensor.b*_sled_korm_2
      - sensor.sh*_vremia
