title: Кормление
views:
  - title: CSV №Загрузка
    path: csv-upload
    icon: mdi:upload
    cards:
      - type: custom:upload-csv-card
  - !include lovelace/tab_pools_1_20.yaml
  - !include lovelace/tab_pools_21_40.yaml
  - !include lovelace/tab_feeding_1_20.yaml
  - !include lovelace/tab_feeding_21_40.yaml
  - !include lovelace/tab_temp_oxy.yaml
  - !include lovelace/tab_pool_1.yaml
  - !include lovelace/tab_pool_2.yaml
  - !include lovelace/tab_pool_3.yaml
  - !include lovelace/tab_pool_4.yaml
  - !include lovelace/tab_pool_5.yaml
  - !include lovelace/tab_pool_6.yaml
  - !include lovelace/tab_pool_7.yaml
  - !include lovelace/tab_pool_8.yaml
  - !include lovelace/tab_pool_9.yaml
  - !include lovelace/tab_pool_10.yaml
  - !include lovelace/tab_pool_11.yaml
  - !include lovelace/tab_pool_12.yaml
  - !include lovelace/tab_pool_13.yaml
  - !include lovelace/tab_pool_14.yaml
  - !include lovelace/tab_pool_15.yaml
  - !include lovelace/tab_pool_16.yaml
  - !include lovelace/tab_pool_17.yaml
  - !include lovelace/tab_pool_18.yaml
  - !include lovelace/tab_pool_19.yaml
  - !include lovelace/tab_pool_20.yaml
  - !include lovelace/tab_pool_21.yaml
  - !include lovelace/tab_pool_22.yaml
  - !include lovelace/tab_pool_23.yaml
  - !include lovelace/tab_pool_24.yaml
  - !include lovelace/tab_pool_25.yaml
  - !include lovelace/tab_pool_26.yaml
  - !include lovelace/tab_pool_27.yaml
  - !include lovelace/tab_pool_28.yaml
  - !include lovelace/tab_pool_29.yaml
  - !include lovelace/tab_pool_30.yaml
  - !include lovelace/tab_pool_31.yaml
  - !include lovelace/tab_pool_32.yaml
  - !include lovelace/tab_pool_33.yaml
  - !include lovelace/tab_pool_34.yaml
  - !include lovelace/tab_pool_35.yaml
  - !include lovelace/tab_pool_36.yaml
  - !include lovelace/tab_pool_37.yaml
  - !include lovelace/tab_pool_38.yaml
  - !include lovelace/tab_pool_39.yaml
  - !include lovelace/tab_pool_40.yaml