title: Кормление
views:
  - title: CSV №Загрузка
    path: csv-upload
    icon: mdi:upload
    cards:
      - type: custom:state-switch
        entity: group
        states:
          admin:
            type: custom:upload-csv-card
  - !include lovelace/tab_pools_1_20.yaml
  - !include lovelace/tab_pools_51_70.yaml
  - !include lovelace/tab_feeding_1_20.yaml
  - !include lovelace/tab_feeding_21_40.yaml
  - !include lovelace/tab_feeding_41_60.yaml
  - !include lovelace/tab_feeding_61_80.yaml
  - !include lovelace/tab_feeding_81_100.yaml
  - !include lovelace/tab_temp_oxy.yaml
  - !include lovelace/tab_sensors.yaml
  - !include lovelace/tab_pool_1.yaml
  - !include lovelace/tab_pool_2.yaml
  - !include lovelace/tab_pool_3.yaml
  - !include lovelace/tab_pool_4.yaml
  - !include lovelace/tab_pool_5.yaml
  - !include lovelace/tab_pool_6.yaml
  - !include lovelace/tab_pool_7.yaml
  - !include lovelace/tab_pool_8.yaml
  - !include lovelace/tab_pool_9.yaml
  - !include lovelace/tab_pool_10.yaml
  - !include lovelace/tab_pool_11.yaml
  - !include lovelace/tab_pool_12.yaml
  - !include lovelace/tab_pool_13.yaml
  - !include lovelace/tab_pool_14.yaml
  - !include lovelace/tab_pool_15.yaml
  - !include lovelace/tab_pool_16.yaml
  - !include lovelace/tab_pool_17.yaml
  - !include lovelace/tab_pool_18.yaml
  - !include lovelace/tab_pool_19.yaml
  - !include lovelace/tab_pool_20.yaml
  - !include lovelace/tab_pool_21.yaml
  - !include lovelace/tab_pool_22.yaml
  - !include lovelace/tab_pool_23.yaml
  - !include lovelace/tab_pool_24.yaml
  - !include lovelace/tab_pool_25.yaml
  - !include lovelace/tab_pool_26.yaml
  - !include lovelace/tab_pool_27.yaml
  - !include lovelace/tab_pool_28.yaml
  - !include lovelace/tab_pool_29.yaml
  - !include lovelace/tab_pool_30.yaml
  - !include lovelace/tab_pool_31.yaml
  - !include lovelace/tab_pool_32.yaml
  - !include lovelace/tab_pool_33.yaml
  - !include lovelace/tab_pool_34.yaml
  - !include lovelace/tab_pool_35.yaml
  - !include lovelace/tab_pool_36.yaml
  - !include lovelace/tab_pool_37.yaml
  - !include lovelace/tab_pool_38.yaml
  - !include lovelace/tab_pool_39.yaml
  - !include lovelace/tab_pool_40.yaml
  - !include lovelace/tab_pool_41.yaml
  - !include lovelace/tab_pool_42.yaml
  - !include lovelace/tab_pool_43.yaml
  - !include lovelace/tab_pool_44.yaml
  - !include lovelace/tab_pool_45.yaml
  - !include lovelace/tab_pool_46.yaml
  - !include lovelace/tab_pool_47.yaml
  - !include lovelace/tab_pool_48.yaml
  - !include lovelace/tab_pool_49.yaml
  - !include lovelace/tab_pool_50.yaml
  - !include lovelace/tab_pool_51.yaml
  - !include lovelace/tab_pool_52.yaml
  - !include lovelace/tab_pool_53.yaml
  - !include lovelace/tab_pool_54.yaml
  - !include lovelace/tab_pool_55.yaml
  - !include lovelace/tab_pool_56.yaml
  - !include lovelace/tab_pool_57.yaml
  - !include lovelace/tab_pool_58.yaml
  - !include lovelace/tab_pool_59.yaml
  - !include lovelace/tab_pool_60.yaml
  - !include lovelace/tab_pool_61.yaml
  - !include lovelace/tab_pool_62.yaml
  - !include lovelace/tab_pool_63.yaml
  - !include lovelace/tab_pool_64.yaml
  - !include lovelace/tab_pool_65.yaml
  - !include lovelace/tab_pool_66.yaml
  - !include lovelace/tab_pool_67.yaml
  - !include lovelace/tab_pool_68.yaml
  - !include lovelace/tab_pool_69.yaml
  - !include lovelace/tab_pool_70.yaml
  - !include lovelace/tab_pool_71.yaml
  - !include lovelace/tab_pool_72.yaml
  - !include lovelace/tab_pool_73.yaml
  - !include lovelace/tab_pool_74.yaml
  - !include lovelace/tab_pool_75.yaml
  - !include lovelace/tab_pool_76.yaml
  - !include lovelace/tab_pool_77.yaml
  - !include lovelace/tab_pool_78.yaml
  - !include lovelace/tab_pool_79.yaml
  - !include lovelace/tab_pool_80.yaml
  - !include lovelace/tab_pool_81.yaml
  - !include lovelace/tab_pool_82.yaml
  - !include lovelace/tab_pool_83.yaml
  - !include lovelace/tab_pool_84.yaml
  - !include lovelace/tab_pool_85.yaml
  - !include lovelace/tab_pool_86.yaml
  - !include lovelace/tab_pool_87.yaml
  - !include lovelace/tab_pool_88.yaml
  - !include lovelace/tab_pool_89.yaml
  - !include lovelace/tab_pool_90.yaml
  - !include lovelace/tab_pool_91.yaml
  - !include lovelace/tab_pool_92.yaml
  - !include lovelace/tab_pool_93.yaml
  - !include lovelace/tab_pool_94.yaml
  - !include lovelace/tab_pool_95.yaml
  - !include lovelace/tab_pool_96.yaml
  - !include lovelace/tab_pool_97.yaml
  - !include lovelace/tab_pool_98.yaml
  - !include lovelace/tab_pool_99.yaml
  - !include lovelace/tab_pool_100.yaml